### ISSUE TITLE
add linting

### ISSUE THREAD

**Issue by dylantyates** [dwreckfoo/portfolio#2]
## Acceptance Criteria
**As a** developer
**I want** to be able to write high quality, consistent code with ease.

## Tasks

- [x] Setup `create-react-app`
- [x] Setup vscode settings and recommended extensions
- [x] Add prettier and eslint dependencies
- [x] Test linting config
